import { env as platformEnv } from 'cloudflare:workers';
import type { Fetcher } from '@cloudflare/workers-types';

export interface BackendEnv {
	PROXMOX_API_URL?: string;
	PROXMOX_EXCLUDED_NODES?: string;
	PROXMOX_SNIPPETS_ENDPOINT_PASSWORD?: string;
	PROXMOX_SNIPPETS_ENDPOINT_URL?: string;
	PROXMOX_SNIPPETS_ENDPOINT_USERNAME?: string;
	PROXMOX_SNIPPETS_ENDPOINT_VERIFY_SSL?: string;
	PROXMOX_SNIPPETS_STORAGE?: string;
	PROXMOX_SNIPPETS_USE_VPC?: string;
	PROXMOX_TOKEN_ID?: string;
	PROXMOX_TOKEN_SECRET?: string;
	PROXMOX_USE_VPC?: string;
	PROXMOX_VM_CPU_TYPE?: string;
	PROXMOX_VM_FIREWALL_SECURITY_GROUP?: string;
	PROXMOX_VPC?: Fetcher;
	SNIPPETS?: Fetcher;
}

export function getBackendEnv(): BackendEnv {
	return {
		PROXMOX_VPC: platformEnv.PROXMOX_VPC,
		PROXMOX_USE_VPC: platformEnv.PROXMOX_USE_VPC,
		PROXMOX_API_URL: platformEnv.PROXMOX_API_URL,
		PROXMOX_TOKEN_ID: platformEnv.PROXMOX_TOKEN_ID,
		PROXMOX_TOKEN_SECRET: platformEnv.PROXMOX_TOKEN_SECRET ?? platformEnv.PROXMOX_API_SECRET,
		SNIPPETS: platformEnv.SNIPPETS,
		PROXMOX_SNIPPETS_USE_VPC: platformEnv.PROXMOX_SNIPPETS_USE_VPC,
		PROXMOX_SNIPPETS_ENDPOINT_URL: platformEnv.PROXMOX_SNIPPETS_ENDPOINT_URL,
		PROXMOX_SNIPPETS_ENDPOINT_USERNAME: platformEnv.PROXMOX_SNIPPETS_ENDPOINT_USERNAME,
		PROXMOX_SNIPPETS_ENDPOINT_PASSWORD: platformEnv.PROXMOX_SNIPPETS_ENDPOINT_PASSWORD,
		PROXMOX_SNIPPETS_ENDPOINT_VERIFY_SSL: platformEnv.PROXMOX_SNIPPETS_ENDPOINT_VERIFY_SSL,
		PROXMOX_SNIPPETS_STORAGE: platformEnv.PROXMOX_SNIPPETS_STORAGE,
		PROXMOX_VM_FIREWALL_SECURITY_GROUP: platformEnv.PROXMOX_VM_FIREWALL_SECURITY_GROUP,
		PROXMOX_VM_CPU_TYPE: platformEnv.PROXMOX_VM_CPU_TYPE,
		PROXMOX_EXCLUDED_NODES: platformEnv.PROXMOX_EXCLUDED_NODES
	};
}
