name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: deploy-production
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up PNPM
        uses: pnpm/setup@4700d737c3d7a2e7199f3d42a920f0bf7f34e411 # v2.0.1
        with:
          cache: true
          runtime: node@lts

      - run: pnpm run check
      - run: pnpm run lint
      - run: pnpm -r build
      - run: pnpm --filter stack-dashboard run db:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: pnpm --filter stack-dashboard run cf:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - run: pnpm --filter stack-dashboard-cron run cf:deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
